### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by Mindavi** [merbanan/rtl_433#1293]
I saw @zuckschwerdt edit the CI file (e475a332affdc279758e09b15708f804a8ef75e9), but I can't find any links to travis (the CI tool). Is CI running or was this only in preparation for use of Travis?

If it's up and running, consider adding a badge or integration so it's open for everyone to see.

**Comment by zuckschwerdt** [comment]
The CI is running at https://github.com/zuckschwerdt/rtl_433 rsp. https://travis-ci.org/zuckschwerdt/rtl_433/branches
Since it deploys binaries I only trigger it on major commits. I'm still experimenting with creating (static) binaries for other platforms (currently only win32).
We might integrate it for checking PRs someday.
