### ISSUE TITLE
LoRa support

### ISSUE THREAD

**Issue by eadmaster** [merbanan/rtl_433#1657]
LoRa seems to use the same frequencies supported by this tool.

An open source decoder is [here](https://github.com/rpp0/gr-lora).

**Comment by zuckschwerdt** [comment]
LoRa is a specific application. Our general case filters and demodulation won't work well.

**Comment by merbanan** [comment]
@zuckschwerdt am I not allowed to work on this you mean ? ;)

**Comment by merbanan** [comment]
![Screenshot from 2021-02-24 12-56-16](https://user-images.githubusercontent.com/124883/108997340-c44a1880-769f-11eb-9af7-56dbd792a23a.png)

Teaser image attached. We'll see where it goes. Demodulation is tricky, but it should be possible to do with the code we have.

**Comment by zuckschwerdt** [comment]
We'd need new filters and demods. And that would be great to have! At least to solidify the idea of different "pipelines" for specific decoders. I'm also lazily working on some filter updates -- it's a little fragile because current setups implicitly assume stuff. E.g. wide bandwidths == wide filters.

One idea I'm toying with is to (automatically) shift the instant phase (pseudo-FFT) results afterwards to apply the low-pass where it's really wanted. (currently the FSK low-pass is adverse for signals that are not centered).

**Comment by merbanan** [comment]
Code we have + rework of the process pipeline.

**Comment by heeplr** [comment]
Are there any news on LoRa support? It'd be awesome!

**Comment by heeplr** [comment]
Adding this for future reference, here's another project that can decode LoRa with RTL dongles: 
https://github.com/hexameron/rtl-sdrangelove/tree/master/plugins/channel/lora
