### ISSUE TITLE
bug on example rtl_433_mqtt_hass.py

### ISSUE THREAD

**Issue by sportchucks** [merbanan/rtl_433#1753]
just a small bug - in rtl_433_mqtt_hass.py the mapping for depth_cm should not include a "device_class": "depth", otherwise you don't get it to Home Assistant. I removed this line and it was working.

**Comment by zuckschwerdt** [comment]
Thanks. Yes, that's not a valid class.
Current allowed classes are listed in 
- https://www.home-assistant.io/integrations/binary_sensor/#device-class
- https://www.home-assistant.io/integrations/cover/#device-class
- https://www.home-assistant.io/integrations/media_player/#device-class
- https://www.home-assistant.io/integrations/sensor/#device-class
- https://www.home-assistant.io/integrations/switch/#device-class

Fixed with f92616d
