### ISSUE TITLE
Is the wetter station WS2320 from MISOL supported? 

### ISSUE THREAD

**Issue by psychos4** [merbanan/rtl_433#2039]
Is the wetter station WS2320 (433 Mhz) from MISOL supported? 

for example: 
https://de.aliexpress.com/item/1005001848787647.html?gatewayAdapt=glo2deu&spm=a2g0o.cart.0.0.2f563c00Pocc7S&mp=1

**Comment by zuckschwerdt** [comment]
That's maybe a rebranded LaCrosse WS2320. The WS2310 is supported. https://github.com/merbanan/rtl_433/blob/master/src/devices/lacrossews.c

**Comment by LeDocteurDesBits** [comment]
Hello, I know that this question is a bit old but I had the same question and it took me a while to find the answer so I thought it would be beneficial to post the answer here. I bought the same weather station (433MHz too) from AliExpress and the station wasn't detected as a WS2320. It seems that these stations are rebranded WH65B (FSK PCM instead of OOK modulation). After enabling the FineOffset WH65B decoder the data are decoded successfully.

**Comment by zuckschwerdt** [comment]
Thank you for the report! I'll add that as note to the decoder.

**Comment by blardyblar** [comment]
I know this question is even older at this point, but I just spent a while getting the "same" weather station from Ali-Express working with RTL_433. It seems the "same" weather station is actually a WS69CN now, and you need the latest code from Dec 15 2025 where support was added for WS69 as the radio packet is slightly different, and the WH65B decoder wasn't decoding it. At the time of this comment, the Debian package was compiled from code on Dec 12 2025, just before the WS69 patch was included. 

I was quite confused until I took the station down physically, and looked at the bottom, where it's actually labeled WS69CN - the Ali listing doesn't specify, and all the info I could find in previous questions about the "same" station that "looks the same" said that it was a WH65B.

Maybe this will save someone else in the future a little time figuring this out
