### ISSUE TITLE
MQTT problem

### ISSUE THREAD

**Issue by giros79** [merbanan/rtl_433#2058]
Hi everybody,
I have a problem, If I run rtl_433 normally everything looks ok 
<img width="537" alt="Schermata 2022-04-26 alle 18 51 08" src="https://user-images.githubusercontent.com/64994156/165352880-798e1f5c-e650-4168-bea4-065da9a47869.png">

but asking mqtt  output (rtl_433 -F "mqtt://192.168.x.xx:1883,user=user,pass=pass,retain=0,devices=rtl_433 214") something goes wrong. Temperature values goes up and down.....
Any suggestion? Could anyone helping me?

Many thanks

<img width="741" alt="Schermata 2022-04-26 alle 18 50 38" src="https://user-images.githubusercontent.com/64994156/165353149-6f43eb09-6921-4947-beaf-400848a2eac3.png">

**Comment by zuckschwerdt** [comment]
I guess you want `rtl_433 -F "mqtt://192.168.x.xx:1883,user=user,pass=pass,retain=0,devices=rtl_433" -R 214`
I don't think you want "rtl_433 214" as the topic name.
Also all devices will report to the same topic there (that's why the temp changes). Best to use something like the default topic (`rtl_433/HOSTNAME/devices[/type][/model][/subtype][/channel][/id]`), maybe `devices=rtl_433[/model][/channel][/id]`
