### ISSUE TITLE
DISCONNECTION

### ISSUE THREAD

**Issue by wackla33** [merbanan/rtl_433#2081]
Hello.  I have running this magnificent integration in HA, on a raspi.  It works very well, except for one problem: from time to time it stops receiving the signals from the different sensors and only shows a kind of status summary every exact 10 minutes.  When that happens, the only way to get it working again is to unplug the pen from the USB port, plug it back in, and then launch the app.  I belong to a group of HA with quite a few colleagues and the same thing happens to most of us.  I've been searching, but I can't find a history of this problem or its possible solution.  Any ideas?  Thank you!

**Comment by gdt** [comment]
Your bug report does not explain in detail what you are actually doing.  It's missing precise RPI config, precise OS, precise rtl_433 version, what code you  are running to transfer data from rtl_433 to HA, and perhaps mostl importantly, which RTL dongle you are using and how you are powering it.

It sounds to me like your problem is no longer getting samples from the RTL dongle, and not about HA integration.   To test, killr tl_433 and restart it.   If that doesn't help, but unplugging/replugging the dongle does, then you have a dongle/power/OS problem, not an rtl_433 problem.   Get a better power supply.

**Comment by wackla33** [comment]
Thanks so much for your message and interest.
