### ISSUE TITLE
which command of intertechno remote is which?

### ISSUE THREAD

**Issue by Marc1200** [merbanan/rtl_433#2442]
Hello, 

i have an klikaanklikuit(Kaku) motion sensor, it has been detected as intertechno-remote. i can see commando's when there is motion and when not. but is there some documentation for each command?
![image](https://user-images.githubusercontent.com/68737063/226676746-3d34672d-d78f-4a4f-8189-8f32e9cdf157.png)

i also get a huge list of intertechno remotes, but i have only 1 motion sensor.
![image](https://user-images.githubusercontent.com/68737063/226676547-fd139b66-ec50-4a7e-9ec0-0c799b7c87e1.png)

**Comment by zuckschwerdt** [comment]
That's a false positive. Grab a sample to know what's really in the transmission. https://triq.org/rtl_433/ANALYZE.html

**Comment by klohner** [comment]
Oops, maybe this?  I guess this makes more sense since it's on 433MHz.

- [KlikAanKlikUit Wireless Motion Sensor AWST-6000 70013 By COCO Smart Home](https://www.massivelighting.co.uk/klikaanklikuit-wireless-motion-sensor-awst-6000-70013-by-coco-smart-home-8836-p.asp)
- [Wireless motion sensor AWST-6000](https://switch-in.eu/en/product/wireless-motion-sensor/)

**Comment by Marc1200** [comment]
@klohner it's indeed the awst-6000

**Comment by Marc1200** [comment]
@zuckschwerdt so i should generate a cu8 sample file for you?

**Comment by zuckschwerdt** [comment]
Yes, please grab a cu8 sample file for the AWST-6000 and check that it looks ok in https://triq.org/pdv/ then upload here as zip.

**Comment by gdt** [comment]
This looks like a timed-out request with no actionable data.

**Comment by gdt** [comment]
abandoned by submitter
