### ISSUE TITLE
Observation about inFactory-TH sensor (protocol 91)

### ISSUE THREAD

**Issue by jpmv27** [merbanan/rtl_433#2972]
I have been using one of these sensors (clone purchased on AliExpress) for a couple of weeks now, and have noted a small number of "false decodes", i.e., invalid messages being incorrectly decoded as valid. I can tell that they are invalid because the decoded ID does not match my sensor's ID, and many of them have unlikely values for the temperature, such as 50, 62, 106, or 150 °C.

I realize that the root cause is likely the weakness of the CRC-4 checksum, and there's nothing we can do to change that.

While it wouldn't eliminate those with reasonable temperatures, would it make sense to add a reasonableness check to the decoder and reject messages with "wild" temperatures?

**Comment by zuckschwerdt** [comment]
Can you record some data codes for the broken transmissions? Verbose mode for the inFactory decoder is `-R 91:v`
If the bit pattern is obviously wrong, e.g. all zeros, then we can add a check. Otherwise we don't really filter and post-process received transmissions -- the data was on-the-air and might mean something to someone, maybe a failing sensor or such.
