### ISSUE TITLE
Auriol temperature sensor Model no Z31743a-TX triggers Prologue callback

### ISSUE THREAD

**Issue by Batilan** [merbanan/rtl_433#45]
I have written a callback for the Auriol temperature sensor Model no Z31743a-TX which works fine. 
This sensor is available in the "Auriol temperature station", the package containing both the sensor and the "base station" is available at e.g. LIDL for € 9,99 (at least in DE and NL).

![auriol-temperaturstation](https://cloud.githubusercontent.com/assets/7621188/3883773/640b88ec-21a5-11e4-9fef-5af012d1018e.jpg)

However when testing and triggering different sensor ID's I found out that it may also trigger the prologue_callback. It might be hard to differentiate the 2 callbacks as both devices send 7 identical packets. The prologue callback is triggered when the mentioned id0 is 1001 (as documented) or 0101  (only in the code), so it has a chance of 1/8 of triggering a "false positive" when it receives packets from the Auriol sensor (can be "fixed" by taking the battery out of the Auriol sensor so it generates a new sensor ID that hopefully does not contain one of the mentioned patterns (might need a few retries).

In the prologue_callback there is a remark "FIXME validate the received message better", any chance of making this happen. I would be glad to assist. 

The Auriol temperature sensor submits only 32 bits, the Prologue temperature sensor submits 36 bits I read, however the bits_per_row is not available to the callback, so it is not an option to check for that when we want to keep the callbacks simple. Any other ideas?

What testing / qualification needs to be done before submitting the code (pull request)?

Attached some output of triggering the prologue callback by the Auriol sensor:

---

```
*** signal_start = 29051340, signal_end = 29280530
signal_len = 229190,  pulses = 233
Iteration 1. t: 102    min: 83 (1)    max: 121 (232)    delta 36
Iteration 2. t: 102    min: 83 (1)    max: 121 (232)    delta 0
Distance coding: Pulse length 102

Short distance: 488, long distance: 977, packet distance: 2319

p_limit: 102

[00] {0} 00 : 00000000
[01] {32} 52 80 df 57 00 : 01010010 10000000 11011111 01010111 00000000
[02] {32} 52 80 df 57 00 : 01010010 10000000 11011111 01010111 00000000
[03] {32} 52 80 df 57 00 : 01010010 10000000 11011111 01010111 00000000
[04] {32} 52 80 df 57 00 : 01010010 10000000 11011111 01010111 00000000
[05] {32} 52 80 df 57 00 : 01010010 10000000 11011111 01010111 00000000
[06] {32} 52 80 df 57 00 : 01010010 10000000 11011111 01010111 00000000
[07] {33} 52 80 df 57 00 : 01010010 10000000 11011111 01010111 00000000

Sensor temperature event at 2014-08-11 20:41:38:
protocol       = Auriol
rid            = 52
temp           = 22.3
Sensor temperature event:
protocol      = Prologue
button        = 0
battery       = Low
temp          = -52.3
humidity      = 112
channel       = 1
id            = 5
rid           = 40
hrid          = 28
52 80 df 57 00
```

---

When the sensor ID changes, it no longer triggers the prologue_callback:

---

```
*** signal_start = 27438007, signal_end = 27660354
signal_len = 222347,  pulses = 233
Iteration 1. t: 93    min: 69 (1)    max: 117 (232)    delta 36
Iteration 2. t: 93    min: 69 (1)    max: 117 (232)    delta 0
Distance coding: Pulse length 93

Short distance: 493, long distance: 981, packet distance: 2323

p_limit: 93

[00] {0} 00 : 00000000
[01] {32} aa 80 d3 a6 00 : 10101010 10000000 11010011 10100110 00000000
[02] {32} aa 80 d3 a6 00 : 10101010 10000000 11010011 10100110 00000000
[03] {32} aa 80 d3 a6 00 : 10101010 10000000 11010011 10100110 00000000
[04] {32} aa 80 d3 a6 00 : 10101010 10000000 11010011 10100110 00000000
[05] {32} aa 80 d3 a6 00 : 10101010 10000000 11010011 10100110 00000000
[06] {32} aa 80 d3 a6 00 : 10101010 10000000 11010011 10100110 00000000
[07] {33} aa 80 d3 a6 00 : 10101010 10000000 11010011 10100110 00000000

Sensor temperature event at 2014-08-11 20:41:31:
protocol       = Auriol
rid            = aa
temp           = 21.1
```

**Comment by valentt** [comment]
I have Auriol weather station and downloading latest rtl_433 source code still doesn't support this sensor. Also downloading @Batilan fork is not working also, but for other resons (compile issues):

`make
/home/ubuntu/toolchain-arm_cortex-a9_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-gcc -c -o obj/rtl-wx.o rtl-wx.c -I. -I/home/ubuntu/toolchain-arm_cortex-a9_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/include/libusb-1.0 -Ilibrtlsdr/include
make: /home/ubuntu/toolchain-arm_cortex-a9_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-gcc: Command not found
Makefile:52: recipe for target 'obj/rtl-wx.o' failed
make: *** [obj/rtl-wx.o] Error 127`

What are you suggestions for others that have this device? How to get support for it?

**Comment by valentt** [comment]
this is what "rtl_433 -a" captures:

`*** signal_start = 34245414, signal_end = 34460872
signal_len = 215458,  pulses = 233
Iteration 1. t: 78    min: 69 (17)    max: 88 (216)    delta 2257
Iteration 2. t: 80    min: 72 (31)    max: 89 (202)    delta 10
Iteration 3. t: 82    min: 74 (49)    max: 90 (184)    delta 5
Iteration 4. t: 83    min: 76 (69)    max: 91 (164)    delta 5
Iteration 5. t: 84    min: 77 (81)    max: 92 (152)    delta 2
Iteration 6. t: 85    min: 77 (94)    max: 93 (139)    delta 1
Iteration 7. t: 86    min: 78 (103)    max: 94 (130)    delta 2
Iteration 8. t: 87    min: 79 (116)    max: 95 (117)    delta 2
Iteration 9. t: 88    min: 80 (131)    max: 96 (102)    delta 2
Distance coding: Pulse length 88

Short distance: 522, long distance: 1011, packet distance: 2348

p_limit: 88

[00] {0} 00 : 00000000 
[01] {32} 94 80 ee 09 00 : 10010100 10000000 11101110 00001001 00000000 
[02] {32} 94 80 ee 09 00 : 10010100 10000000 11101110 00001001 00000000 
[03] {32} 94 80 ee 09 00 : 10010100 10000000 11101110 00001001 00000000 
[04] {32} 94 80 ee 09 00 : 10010100 10000000 11101110 00001001 00000000 
[05] {32} 94 80 ee 09 00 : 10010100 10000000 11101110 00001001 00000000 
[06] {32} 94 80 ee 09 00 : 10010100 10000000 11101110 00001001 00000000 
[07] {33} 94 80 ee 09 00 : 10010100 10000000 11101110 00001001 00000000`

**Comment by deennoo** [comment]
Try this version : 
https://github.com/pm-cz/rtl_433

**Comment by valentt** [comment]
@deennoo thanks for the tip, after compiling and running this version of rtl_433 this is what I get:

```
Sensor temperature event:
protocol      = Prologue
button        = 0
battery       = Low
temp          = 142.7
humidity      = 96
channel       = 1
id            = 9
rid           = 72
hrid          = 48
94 80 59 36 00
```
Which is obviously too high temperature because outside temperature is currently 10°C

And this is output from ```rtl_433 -a``` command:

```
*** signal_start = 1536940, signal_end = 1738739
signal_len = 201799,  pulses = 233
Iteration 1. t: 80    min: 66 (5)    max: 94 (228)    delta 841
Iteration 2. t: 80    min: 66 (5)    max: 94 (228)    delta 0
Distance coding: Pulse length 80

Short distance: 516, long distance: 1003, packet distance: 2347

p_limit: 80

[00] {0} 00 : 00000000 
[01] {32} 94 80 80 31 00 : 10010100 10000000 10000000 00110001 00000000 
[02] {32} 94 80 80 31 00 : 10010100 10000000 10000000 00110001 00000000 
[03] {32} 94 80 80 31 00 : 10010100 10000000 10000000 00110001 00000000 
[04] {32} 94 80 80 31 00 : 10010100 10000000 10000000 00110001 00000000 
[05] {32} 94 80 80 31 00 : 10010100 10000000 10000000 00110001 00000000 
[06] {32} 94 80 80 31 00 : 10010100 10000000 10000000 00110001 00000000 
[07] {33} 94 80 80 31 00 : 10010100 10000000 10000000 00110001 00000000 
```

**Comment by deennoo** [comment]
What is your sensor type ? Référence, Ian, all is write on your sensor.

Try to Google : sensor id and arduino, i got a succès with this for a friend of mine.

**Comment by valentt** [comment]
Sensor model is Z31743B-TX (version 09/2013). Here are data dumps with temprature readings from station: http://pastebin.com/DPq160e3 and also raw data dump - http://pastebin.com/ZWBCTXHt

I have wrote also a blog post on this topic - http://kernelreloaded.com/reading-temperature-data-from-auriol-temperature-station-via-rtl_433/

It looks like converting third octet from binary to decimal gives temperature, did I correctly conclude this?

**Comment by deennoo** [comment]
Great you got your temp with b2 ! 

Just a matter of decoding now ! (Can't help i'm not a killer on programing)

I try to help Nodotrx project (rfxcomtrx like but homemade http://www.listenlive.nl/blog/  he just discover RTL sdr capability and can be helpfull).

**Comment by Batilan** [comment]
@valentt, Nice article! Its always nice to find out the required decoding yourself. You are almost there! However when temperatures rise above 25.5 degrees again it will suddenly get cold again ;-)

The code at https://github.com/Batilan/rtl_433/blob/plugins/src/plugin/plugin_auriol.c should be OK for this sensor. Currently it is only in my branch (and in my rtl-wx branch).

**Comment by Batilan** [comment]
@valent Note that it is also possible to compile my rtl-wx repo when you first switch to the auriol-Z31743a-TX branch by using the command 'git checkout auriol-Z31743a-TX' first.

If you would like to use my rtl_433 version with plugins then use 'git checkout plugins' first. Then you can enable or disable several plugins by removing plugins from /usr/local/lip/plugins (after make install)

**Comment by papadeltasierra** [comment]
I've cracked the checksum for the Auriol sender, as used with LD2569 (e.g. 4-LD2569-2) devices.  It works as follows:
- Create your 24 bits of data (see below)
- Create a starting 8-bit checksum of 0x00
- Repeat the following 40 (forty) times (the last 16 times you will have no new data to add!)
  - If the top bit (0x80) of the checksum is set, XOR the checksum with 0x18
  - Rotate the checksum left (bringing the now '9th' bit back to the bottom bit).
  - XOR in the current top bit of the data into the bottom bit (0x01) of the checksum
  - Shift the data left 1 and AND with 0xFFFFFF (discarding the bit you just used)
- Now the 32-bit data is the 24-bit starting data, ORed with the checksum.

BUT are there any mathematicians out there because if so, some questions for you:

1. How come this ALWAYS creates a 32-bit value that has even parity?  The bottom bit is NOT a parity bit, but it does appear like one!
2. Any way to avoid the final 16-rotate where we are bringing in new data?
3. Is there a more efficient method to generating the same checksum?

Now, that 24 bits of data...
- bits 0-7 - Random value (never 0x00) set when inserting batteries
- bit 8 - Manual/automatic data send (assume '1' means 'manual' - can someone confirm?)
- bit 9 - Low battery; also causes a beep from the receiver.  Low battery is only cleared by resetting the sender/receiver.
- bits 10-11 - channel.
- bits 12-23 - temperature in 'degC x 10'.
  - 0x800 bit set indicates 'negative' in which case the true temperature is 'negative 0x1000 - value'.
- bits - 24-31 - checksum as described above.

Enjoy!
papadeltasierra.

**Comment by zuckschwerdt** [comment]
Execute the shift (was rotate) before the xor and only xor if the original top-bit (drops off) differs from the next data bit, and now you got a CRC. The poly should be something like 110001b -- maybe... just a thought that came to mind. Might be worth trying to express/test this as CRC.

**Comment by papadeltasierra** [comment]
Christian,

Interesting.  Do you know of any CRCs that ‘fake’ extra data?  It was the extra 16 steps that threw me because logically the input data for a CRC becomes 0xDDDDDD0000 where DD implies real data.
Paul DS.

**Comment by papadeltasierra** [comment]
Curses! The encoding/protocol is even more cunning.  This encoding (with changes - see below) works for the initial transmission but not for following transmissions.  Is anyone able to post a sequence of transmissions, ideally with the temperature changing?
Also, using the same nomenclature as before:
Bit 8 is the battery condidion flag with '1' indicating good and '0' indicating low.
Bit 9 bleeps, but seems to have no other function.

**Comment by MswPaulDSmith** [comment]
I'm beginning to think it's my transmitter that is at fault.  Is anyone able to indicate what the 233 pulses that you see are (I don't have a working genuine transmitter - I've creating one from an Arduino).  Counting off I expect:

7 x (1 + 32) = 7 frame of (long start pulse + 32 data pulses) = 231

So what are the other two pulses?

**Comment by papadeltasierra** [comment]
Anyone got a 'picture' of the raw pulses?  I need to see how the frame(s) are started and ended.

**Comment by papadeltasierra** [comment]
OK, this is frustrating!  Firstly, bit 8 is the 'low battery' indicator and bit '9' just makes the receiver beep.   And with this, and sending using DMA to get an accurate signal and repeating 7 times as per the items above, the first send ALWAYS works.  Now it gets odd...
If I set the 'beep' flag (risking irritating everyone within earshot) then the transmission always seems to work, but since I get multiple beeps (between 2 and 4 normally), the sensor must be managing to catch multiples of the retransmissions.  Now turn the beep flag off, and the sensor only works very rarely, missing almost all the transmissions except for the first one which still always works.
Has anyone got the slightest idea what I might be missing from the transmissions?  What I'm assuming is:
pulse, long frame start,
32 times pulse, zero/one low
repeat above 7 times
final pulse to terminate the last frame.

**Comment by papadeltasierra** [comment]
Aha - there's nothing wrong with my transmitter, the problem is the receiver.  It seems that the Auriol base station only provides power to its 433MHz receive module every 30s (or so - still trying to get a precise reading!).  So unless sending the data is synced with this schedule, no new data is received.  That explains the occasional random receipt of data, and also why the first transmission ALWAYS works - the receiver is in 'sync up' mode and keeps listening until the first data arrives.

**Comment by merbanan** [comment]
This method help reduce collisions and gives better battery life.

**Comment by papadeltasierra** [comment]
Agreed but it does require the receiver and transmitter to be carefully designed as a single unit and then the receiver to keep sync with the transmitter to avoid drift.  I had a quick play yesterday but haven't managed to get the timings right on my transmitter so I'm immediately out of sync.  I need to get some more accurate timings to figure out how to schedule the transmitter.

**Comment by MswPaulDSmith** [comment]
A final comment.  The encoding is correct and the last piece of the puzzle if you are making a transmitter is to transmit every 31s.  Note that this means that you start each set of transmissions 31s after you started the last one - key this time off the START of each transmission and not the END of the last transmission because transmission lengths will changed because different values encode to 433MHz encodings of different length/times so the ends shift relative to the start.
Yesterday I had one of these weather stations in my office tracking my homebrew transmitter all day, the data for the homebrew transmitter being the temperature in my garden a mile away.  The temperature was "transmitted" via a different homebrew 433MHz receiver with the two homebrew boxes communicating via the 'Weather Underground' website, the receiver uploading temperature data which the sender downloaded and then transmitted to the weather station on my office desk.

**Comment by jose1711** [comment]
@MswPaulDSmith could you please share details on how you made the transmitter? thank you, jose

**Comment by MswPaulDSmith** [comment]
I used a transmitter similar this this (there are a number of variants).
https://www.ebay.co.uk/itm/5PCS-433Mhz-RF-transmitter-and-receiver-link-kit-Arduino-ARM-MC-U-remote-control/181887579863?hash=item2a595836d7:g:GwkAAOSwrFtZ-76w
I drive this from an ESP8266 pin using DMA to drive PWM.  The minimum clock rate is far too high so each '1' that I want to send is actually represented as 16 '1's in the data I send to the DMA (zeros are also 16x of course).  Sending 16x 1s fast justs appears as a single long 1 on the output pin.
Use something like an ESP8266 variant 12 or 13 (not a 01!) so that you have enough pins to be able to set function (load new firmware etc) as well as having a free DMA/PWM pin.  Other than pull down resistors and a 5V/3.3V regulator, there's nothing more to it.  I created a simple antenna from about 18cm of wire rolled into a coil.  The transmitter sends over at least 10m.
Hard bit is getting the ESP8266 to drive the DMA, especially resetting it - my code works about 99.9% of the time but there's clearly something not quite right because it locks up occasionally.

**Comment by jose1711** [comment]
@MswPaulDSmith thank you, tbh i have no electrical engineering background and lot to study. in a similar experiment i have tried to replicate signal sent by a remote using raspberry pi (pigpio python library) only to find that my "zeroes and ones" always take longer that the ones that remote generates. there are plenty or projects dealing with analyzing the rf signal but it gets very scarse when you want to transmit. if there's something you can recommend (maybe forget about raspberry pi), please share. thanks again, j

**Comment by MswPaulDSmith** [comment]
Jose, if you are interested in this specific project then this thread has plenty of links to 'here's what the signal should look like'.  If you have a different project in mind then you need some way of sniffing the signal.  I have used an Arduino to catch signals and drop 'microsecond, on/off' logs quite successfully for 'slow' protocols like infra-red remotes or these temperature sensors.  After that it's a case of find suitable computer code to modify to get (typically) DMA to drive the signals so that they are precise and not messed up by the processor going off to do other things (Linux etc multi tasks of course by taking the CPU away from you to do other things!).
As for timings, you need to understand how the DMA works.  Typically you set:
- The base speed, i.e. 1/0 width based on a clock and...
- One or more dividers so you might start with 10MHz, divide by 1000 and end up with a 10kHz clock.
Often you can't get slow enough so you then scale your signal up so instead of sending a single 1010 you send
11111111000000001111111100000000
and run the clock (in this case) 8 times faster than you really want.
So off to Google with you - both the Raspberry PI and the ESP8266 have some DMA code out there that you can start from.  Figure out what it does and why, and then you can start tinkering with it.  But you do need to understand it before you start otherwise you will never get it to work - I speak from experience!

**Comment by zuckschwerdt** [comment]
Things to look at for TX: CC1101 boards (RF100se) and HopeRF RFM69W boards. Those do the timing on-board and are connected by I2C/SPI. But you have to programm the timing and control the fifo buffers.

**Comment by cityba** [comment]
Hello Bpi board write RCSwitch.cpp help me , what protocol??
`#ifdef ESP8266
static const RCSwitch::Protocol proto[] = {
#else
static const RCSwitch::Protocol PROGMEM proto[] = {
#endif
    { 350, {  1, 31 }, {  1,  3 }, {  3,  1 } },    // protocol 1
    { 650, {  1, 10 }, {  1,  2 }, {  2,  1 } },    // protocol 2
    { 100, { 30, 71 }, {  4, 11 }, {  9,  6 } },    // protocol 3
    { 380, {  1,  6 }, {  1,  3 }, {  3,  1 } },    // protocol 4
    { 500, {  6, 14 }, {  1,  2 }, {  2,  1 } },    // protocol 5
};
`
What protocol receive signal?

**Comment by zuckschwerdt** [comment]
Is this question about rtl_433? Best to ask on the rc-switch project.

**Comment by cityba** [comment]
Sorry no run rtl433 bpi board :( please help me! thanks
