### ISSUE TITLE
No supported device

### ISSUE THREAD

**Issue by powslang** [merbanan/rtl_433#46]
Hi there, new to Linux and rpi. 
Installed rtl433 on my rpi with a 433mhz rx/TX chip on breadboard. But when I execute ./rtl_433 it's says no supported device. What am I doing wrong?

**Comment by merbanan** [comment]
433mhz rx/TX chip on breadboard is not supported, yet.

**Comment by tonyfitzs** [comment]
Hi there I am trying to get rtl_433 working with my RTL R820T clone SDR, but I am getting lots of odd errors and I can’t work out what I’m doing wrong. My Linux skills are not great so that is compounding things.  
First off, I have tested my SDR using SDRConsole, and I can tune up to all kinds of fun things I am able to successfully tune to 433.965 mhz and I can hear my two motion sensors chirping away happily when triggered, I can also tune to 433.986 Mhz and can hear a door sensor as well. So I am confident there is noting wrong with my SDR device and I know that my sensors are working. 
I have been following this tutorial https://guti.in/posts/2020-07-11-rtl-sdr-rpi-influxdb-temperature-monitoring/ and I am able to successfully install the RTL-SDR and rtl_433 components. 

When I attempt to run rtl_433 as per the instructions, I get the following startup message.

rtl_433 version 20.02-144-g3fc80d4 branch master at 202009051935 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/home/pi/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Registered 137 out of 166 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-166 ]
Detached kernel driver
Found Rafael Micro R820T tuner
r82xx_write: i2c wr failed=-1 reg=0c len=1
r82xx_init: failed=-1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
Exact sample rate is: 250000.000414 Hz
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
r82xx_write: i2c wr failed=-1 reg=0a len=1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
WARNING: Failed to set sample rate.
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
r82xx_write: i2c wr failed=-1 reg=05 len=1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
WARNING: Failed to enable automatic gain.
rtlsdr_write_reg failed with -1
rtlsdr_write_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
r82xx_write: i2c wr failed=-1 reg=17 len=1
r82xx_set_freq: failed=-1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
WARNING: Failed to set center freq.
Sample buffer too short!

The “Sample buffer too short!” repeats itself 20 or 30 time ( the screen buffer runs out so I can’t tell exactly), then I get the following

Sample buffer too short!
Async read stalled, exiting!

LIBUSB_ERROR_NOT_FOUND: Entity not found!
Check your RTL-SDR dongle, USB cables, and power supply.

WARNING: async read failed (-5).
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_demod_write_reg failed with -1
rtlsdr_demod_read_reg failed with -1
rtlsdr_write_reg failed with -1
Reattaching kernel driver failed!__

So it seems clear that the USB device is not connected or is disconnecting as a result of the buffer error…. when I issue the command lsusb then I confirm this is true, however, if I disconnect the radio and then reconnect it again I can see the following when I issue the lsusb command again

Bus 001 Device 027: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T

If I again try issuing rtl_433 I get the exact same error as shown above. I have spent many hours trying to work this out but have not had any success, is it possible to get some guidance as to what is going wrong?

**Comment by zuckschwerdt** [comment]
This is unrelated to the topic, a new issue would have been appropriate. That's not an error with rtl_433, e.g. rtl_sdr wouldn't work either I guess. Looks like something is interfering, did you forget to remove/blacklist the DVB drivers? (try `lsmod` to check)

**Comment by tonyfitzs** [comment]
Hi Christian, thanks for the replay. my humble appologies, I had several different pages open and I pasted the error into the wrong one sorry. if it helps I am happy to post this to the corect page. 

you have mentioned about blacklisting the DVB drivers! i have not seen any referaance to anything I have read that says I need to do that, so this might be the issue. I am trying to go back a few steps and see if I can use different approch to getting this working. i.e trying to see if I can find a native Linux tool that I can use to test things before going to the rtl_433. i found this tutorial https://sdr-setup-notes.readthedocs.io/en/latest/about.html so I will try this now and loop back around if I need to. you can close this issue as I will open it in the corect place if I need to. thanks

**Comment by zuckschwerdt** [comment]
Yes, the steps for removing the DVB TV modules are listed there https://sdr-setup-notes.readthedocs.io/en/latest/dev_rtlsdr.html -- you might need to reboot, and you can check if the modules are loaded (and thus blocking access) by using `lsmod` and looking for "dvb" or "rtl" lines. Generally you don't want "dvb_usb_rtl28xxu" to be loaded. You should be able to unload that with just `rmmod -v dvb_usb_rtl28xxu`
Btw, rtl_433 and rt_sdr use the same mechanism to operate the RTL-SDR, so either should work. I don't know of any "native" tool.

**Comment by tonyfitzs** [comment]
thanks very much for your help

**Comment by Mazufa** [comment]
Hi!

Could someone please confirm if this rtl_433 supports this particular radio dongle: https://www.ebay.com/itm/276000566513

Thanks!
