### ISSUE TITLE
stderr: "Async read stalled, exiting!"

### ISSUE THREAD

**Issue by blotsome** [merbanan/rtl_433#718]
I am using JohnV81's [Raspberry Pi RF Temperature monitor](https://www.instructables.com/id/Raspberry-Pi-RF-Temperature-Monitor/), I'm using a pair of Acurite 986 temp sensors, and I am getting  "stderr: Async read stalled, exiting!" showing  up in the log file of record_986.py. Googling the error showed me it is related to rtl_433 and that it "requires callback to run every 3 second, abort otherwise". Any idea what could be the root cause of this and how to address? would changing the alarm(3) to a long period do anything, or would it risk missing samples or cause other issues?

record_986.py is started on reboot by cron, and runs continuously, but it seems to hang/exit on this error. I was thinking of restarting the process or rebooting every time this happens (which is about every 3 hours give or take). But again, I think identifying the root cause is better than any of these possible workarounds.

**Comment by zuckschwerdt** [comment]
Related: #610 and #593 
Basically the dongle stopped sending data. Remove or relax the timeout and rtl_433 will just sit there dead. The root cause could be something wrong with the USB stack or the dongle actually crashed. This happend with my dongles quite often on higher sample rates because of overheating. The real fix there was to stick a heatsink to the R820T.
And I'd suggest not using pipes but to run two seperate processes, preferably with supervision (e.g. [supervisord](http://supervisord.org/)). Let rtl_433 send the data via syslog protocol and the python script consume that. See e.g. https://github.com/zuckschwerdt/rtl_433_relay/blob/master/rtl_433_graphite_relay.py

**Comment by blotsome** [comment]
Maybe I just need another dongle then. You say higher sample rates were causing overheating for you, how would I adjust sample rate? I'll definitely read up on two separate processes, supervision, and syslog protocol, but all that is clearly above my current skill level and knowledge. I want to learn more, so I will try to figure that stuff out, but if it's a faulty dongle, seems like an easy immediate fix for my breastmilk freezer alarm. Don't want to risk loosing my baby's food.

**Comment by zuckschwerdt** [comment]
The basic idea is to let the program crash on error and restart it cleanly. The latter is easy done with supervisord: `apt get install supervisord` and then add the program there instead of starting it once  in a boot script (with gnome-schedule). Add something like
```
[program:my_program]
command=/home/pi/record_986.py
```
to /etc/supervisor/conf.d/my_program.conf

You the just need to make sure the program exits when the pipe to rtl_433 crashes.

**Comment by blotsome** [comment]
I ended up using  this for my conf, and it has been up for 4 days with no async errors:
```
[program:my_program]
command=python /home/pi/FreezerProjects/record_986.py
stderr_logfile=/home/pi/logt986_err.log
stdout_logfile=/home/pi/logt986_out.log
autostart=true
```
Thanks for the support.

**Comment by zuckschwerdt** [comment]
One last thing to test: pull the receiver dongle out while the program is running. Make sure the program crashes (`supervisord status`). Insert the dongle again and see if there is a clean restart. You might need to tune the [`startretries`](http://supervisord.org/configuration.html#program-x-section-settings) setting if the dongle is disconnected for some time.
