### ISSUE TITLE
segfault when compiling under amd64

### ISSUE THREAD

**Issue by SledgehammerPL** [merbanan/rtl_433#72]
Does any have an idea why rtl_444 generates segfault? I use it under i386, but moved into amd64, githubbed clean repo, cmake, make, rtl_433 -> 
Registering protocol[01] Rubicson Temperature Sensor
Registering protocol[02] Prologue Temperature Sensor
Registering protocol[03] Silvercrest Remote Control
Registering protocol[04] ELV EM 1000
Registering protocol[05] ELV WS 2000
Registering protocol[06] Waveman Switch Transmitter
Registering protocol[07] Steffen Switch Transmitter
Registering protocol[08] Acurite 5n1 Weather Station
Segfault

dmesg shows:

[14190.217587] rtl_433[21585]: segfault at 0 ip 00007fa33d944294 sp 00007fff96da4e90 error 4 in libc-2.13.so[7fa33d89c000+182000]
[14195.813128] rtl_433[21586]: segfault at 0 ip 00007f163b58d294 sp 00007fff494fab00 error 4 in libc-2.13.so[7f163b4e5000+182000]
[14220.146136] rtl_433[21592]: segfault at 0 ip 00007f67074c7294 sp 00007fff670af930 error 4 in libc-2.13.so[7f670741f000+182000]
[14857.105725] rtl_433[22594]: segfault at 0 ip 00007f5a2bb51294 sp 00007fff6edad4e0 error 4 in libc-2.13.so[7f5a2baa9000+182000]

**Comment by loewal** [comment]
Hi there,
Having next problem running RTL_433 with a Hackrf (with Furrtek Havoc firmware):
[INFO] Opening HackRF One #0 223c69dc299f894f...
Using device HackRF One: clock source=external part id=a000cb3c0065434d serial=0000000000000000223c69dc299f894f version=local-79baef77
Found 1 antenna(s): TX/RX
Found 3 gain(s): LNA 0 - 116 (step 0) AMP 0 - 116 (step 0) VGA 0 - 116 (step 0)
Found 1 frequencies: RF
Found 1 frequency range(s): 0 - 7250000000 (step 0)
Found 20 sample rate range(s): 1000000 2000000 3000000 4000000 5000000 6000000 7000000 8000000 9000000 10000000 11000000 12000000 13000000 14000000 15000000 16000000 17000000 18000000 19000000 20000000
Found 16 bandwidth range(s): 1750000 - 1750000 (step 0) 2500000 - 2500000 (step 0) 3500000 - 3500000 (step 0) 5000000 - 5000000 (step 0) 5500000 - 5500000 (step 0) 6000000 - 6000000 (step 0) 7000000 - 7000000 (step 0) 8000000 - 8000000 (step 0) 9000000 - 9000000 (step 0) 10000000 - 10000000 (step 0) 12000000 - 12000000 (step 0) 14000000 - 14000000 (step 0) 15000000 - 15000000 (step 0) 20000000 - 20000000 (step 0) 24000000 - 24000000 (step 0) 28000000 - 28000000 (step 0)
Found current bandwidth 0
Found 4 stream format(s): CS8 CS16 CF32 CF64
Found native stream format: CS8 (full scale: 128.0)
zsh: **segmentation fault**  rtl_433 -d driver="hackrf" -g "LNA=40,AMP=14,VGA=30" -M newmodel -vvv

What could be the problem.
My Hackrf is found, but the command

~/ soapysdrutil --probe="hackrf"
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

Probe device hackrf
[INFO] Make connection: ''
Error probing device: Failed to make connection with ''

Gives no Hackrf....
Anyone??

**Comment by loewal** [comment]
forgot this:
~/ hackrf_info
hackrf_info version: unknown
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000223c69dc299f894f
Board ID Number: 2 (HackRF One)
Firmware Version: local-79baef77 (API:1.03)
Part ID Number: 0xa000cb3c 0x0065434d

**Comment by zuckschwerdt** [comment]
Can you try a full debug build (`cmake -DCMAKE_BUILD_TYPE=Debug .. && make` from the ./build dir)?

**Comment by loewal** [comment]
The result:
Found current bandwidth 0
Found 4 stream format(s): CS8 CS16 CF32 CF64
Found native stream format: CS8 (full scale: 128.0)
AddressSanitizer:DEADLYSIGNAL
=================================================================
==18757==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fff66b27c92 bp 0x7ffee3bfa080 sp 0x7ffee3bfa080 T0)
==18757==The signal is caused by a READ memory access.
==18757==Hint: address points to the zero page.
    #0 0x7fff66b27c91 in _platform_strlen (libsystem_platform.dylib:x86_64+0x1c91)
    #1 0x10c660309 in wrap_strlen (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x18309)
    #2 0x10c60c6f3 in SoapySDRDevice_setupStream (libSoapySDR.0.8.0.dylib:x86_64+0x1b6f3)
    #3 0x10c1d678f in sdr_open_soapy sdr.c:692
    #4 0x10c1d2f2e in sdr_open sdr.c:796
    #5 0x10c1b42fa in main rtl_433.c:1476
    #6 0x7fff669317fc in start (libdyld.dylib:x86_64+0x1a7fc)

==18757==Register values:
rax = 0x000000010d2f968c  rbx = 0x0000615000005000  rcx = 0x0000000000000001  rdx = 0x0000000000000001
rdi = 0x0000000000000000  rsi = 0x00006070000007a0  rbp = 0x00007ffee3bfa080  rsp = 0x00007ffee3bfa080
 r8 = 0x0000000000000000   r9 = 0x0000000000000000  r10 = 0x00007fff9075f1e0  r11 = 0x000000010c60c6a0
r12 = 0x000000010d2f9688  r13 = 0x0000000000000001  r14 = 0x0000000000000001  r15 = 0x0000000000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_platform.dylib:x86_64+0x1c91) in _platform_strlen
==18757==ABORTING
zsh: abort      rtl_433 -d driver="hackrf" -g "LNA=40,AMP=14,VGA=30" -M newmodel -vvv
