### ISSUE TITLE
[feature request] Option to get back frequency where signal was found

### ISSUE THREAD

**Issue by solsticedhiver** [merbanan/rtl_433#944]
From my understanding, it seems **rtl_433** seems to scan a certain bandwidth even if you specify a given frequency with `-f`

I would have liked to get back the frequency at which the decoded signal was found.

Because I see multiple signal on different frequencies, and rtl_433 gives them back to me at whichever frequency I use, and I can't discrimante them. I have tried to run rtl_433 with different -f value but it's the same.

Note: If that matters, I use a rtl-sdr.com dongle with a 2.33MHz bandwidth

**Comment by zuckschwerdt** [comment]
The frequency given with `-f` is really a center frequency. The sample rate then sets the window.
Since we get complex I/Q samples the cutoff is at the full sample rate (in contrast to half the sample rate for real valued signals).
For the default 250 kHz sample rate and 433.92 MHz center frequency you get signals from 433.795 to 434.045 MHz. However signals right at the "edges" or dead center won't really work.

There is no scanning (you can get hopping with multiple `-f`), there is no "true" frequency for a signal (you can get an estimate with `-M level` though).
